services:
  api:
    build: .
    container_name: karhub-beer-api
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: "8080"

      # Spotify credentials
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}

    restart: unless-stopped
